id: IB788BB94
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T04:59:38+00:00'
last_modified: '2022-06-10T13:06:39.038581+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W9209
  title: མཁའ་འགྲོ་གསང་བ་ཡེ་ཤེས་ཀྱི་ཆོས་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    70D0:
      image_group_id: I3083
      title: ''
      total_pages: 740
      order: 1
      base_file: 70D0.txt
    '8868':
      image_group_id: I3084
      title: ''
      total_pages: 652
      order: 2
      base_file: 8868.txt
    43A3:
      image_group_id: I3085
      title: ''
      total_pages: 602
      order: 3
      base_file: 43A3.txt
    591B:
      image_group_id: I3086
      title: ''
      total_pages: 524
      order: 4
      base_file: 591B.txt
    D345:
      image_group_id: I3087
      title: ''
      total_pages: 526
      order: 5
      base_file: D345.txt
    A0A9:
      image_group_id: I3088
      title: ''
      total_pages: 888
      order: 6
      base_file: A0A9.txt
    00D5:
      image_group_id: I3089
      title: ''
      total_pages: 526
      order: 7
      base_file: 00D5.txt
    06A8:
      image_group_id: I3090
      title: ''
      total_pages: 584
      order: 8
      base_file: 06A8.txt
    1A17:
      image_group_id: I3091
      title: ''
      total_pages: 508
      order: 9
      base_file: 1A17.txt
    288D:
      image_group_id: I3092
      title: ''
      total_pages: 506
      order: 10
      base_file: 288D.txt
    CA4C:
      image_group_id: I3093
      title: ''
      total_pages: 486
      order: 11
      base_file: CA4C.txt
    A8D4:
      image_group_id: I3094
      title: ''
      total_pages: 536
      order: 12
      base_file: A8D4.txt
    AFD7:
      image_group_id: I3095
      title: ''
      total_pages: 566
      order: 13
      base_file: AFD7.txt
    AA49:
      image_group_id: I3096
      title: ''
      total_pages: 444
      order: 14
      base_file: AA49.txt
    9C5C:
      image_group_id: I3097
      title: ''
      total_pages: 412
      order: 15
      base_file: 9C5C.txt
    AB91:
      image_group_id: I3098
      title: ''
      total_pages: 448
      order: 16
      base_file: AB91.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
